AWSTemplateFormatVersion: 2010-09-09

Mappings:
  RegionMap:
    us-east-1:
      HVM64: ami-0c2b8ca1dad447f8a 
    us-east-2:
      HVM64: ami-0233c2d874b811deb     
      
Parameters:
  MyKeyName:
    Description: Select the key from the list in the console
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  StackEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: t2.micro